nvimdev/lspsaga.nvim

- lua/lspsaga/provider.lua
For many servers this will be a mandatory value that needs to be
set with the request or they will return null as a value.
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references
Fixes #16
> Add in context to reference request.

- README.md
Nitpick...
Btw: I can't find it in the docs, but I think if you use the `<cmd>` prefix (which has many advantages next performance) you don't need to silence the commands. You use silence for with and without the `<cmd>`. Do you really need it? :thinking:  And is there a specific reason you mixed both variants? Just asking... :speak_no_evil:
> Fix typo in README for LspSagaRename command name

- README.md
- lua/lspsaga/libs.lua
This closes #57
This makes a few changes to the current `server_filetype_map`
functionality.
1. The logic used to be that you checked for `client.root_dir` first,
and if that wasn't found, then you would look into the map. Instead,
you should look to see if `config.filetypes` is defined first, if
not, then you look into the map.
2. Instead of using `config.cmd` in the mapping, use `config.name`.
Mainly because you can't always rely on `config.cmd` being a single
executable. In the case of `nvim-metals` is a full path, in
`nvim-jdtls` is a path to a script. So if you use name, the mapping
becomes much simpler.
3. Swap around the value and key in the mapping so that a single server
name can point to multiple filetypes. This is inline with how
`config.filetypes` is, so probably best to keep …
> Fix server_filetype_map.

- lua/lspsaga/hover.lua
Hey @glepnir , I'd like to be able to do this:
```lua
vim.lsp.handlers["textDocument/hover"] = require('lspsaga.hover').handler
```
to be able to to make `lspsaga` just integrate into the rest of my builtin LSP stuff.
In general, I think it'd be cool to expose the handlers to be consumed a bit more independently if you don't mind.
Anyway, thanks, just checking out the plugin today :)
> feat: Expose hover handler to be used as a handler

- lua/lspsaga/diagnostic.lua
Just encountered an error when jumping to diagnostics
[![asciicast](https://asciinema.org/a/lZxa88F4hzmeCLLNm9FaQVMQE.svg)](https://asciinema.org/a/lZxa88F4hzmeCLLNm9FaQVMQE)
`E5108: Error executing lua ...ack/packer/start/lspsaga.nvim/lua/lspsaga/diagnostic.lua:137: attempt to concatenate local 'server_source' (a nil value)`
> Fix jump to diagnostics error

- README.md
- lua/lspsaga/window.lua
- lua/lspsaga/wrap.lua
Thank you for creating a very cool plugin!
I am using `set ambwidth=double` and am having problems with the display broken.
Therefore, ascii characters can now be used in `border_style`.
Also, when `border_style=4`, ascii characters will be used in `wrap.lua`.
**Screenshot**
before: `border_style=1`
after: `border_style=4`
> feat: add `border_style=4` (ascii border)

- lua/lspsaga/window.lua
Links the NormalNC highlight group as well to prevent NormalNC from
overriding the highlighting in floating windows.
> Set NormalNC as well as Normal in winhl

- lua/lspsaga/diagnostic.lua
Thank you for the plugin!
I suggest to jump to the first/last element of diagnostics messages if there are no messages above/below.
> Add circular diagnostics jumps

- lua/lspsaga/libs.lua
- lua/lspsaga/provider.lua
vim.loop.os_uname().sysname appears to return "Windows_NT", so the
in_windows check was changed to check for a substring instead of
straight equality. This was also migrated to a function to perform a
similar check in provi.ers.lua.
os.getenv("HOME") returns nil on Windows. os.getenv("USERPROFILE") is
appropriate on Windows.
vim.uri_to_fname() returns paths with lowercase drive letters on Windows
for some reason. Before the paths are shortened for the lsp_finder
results, a check for Windows was added, along with a substitution of the
drive letter for the appropriate uppercase version.
I'm no lua wizard, but I took a swing at it. I'm not sure if I caught all the Windows edge cases. I basically just worked through the hangups until I got lsp_finder working. Let me know if there is something …
> Windows lsp_finder fixes

- lua/lspsaga/diagnostic.lua
First off, love the plugin!
I wanted something similar to my CoC setup which shows all LSP diagnostics under the cursor position. I don't _think_ there is a way to do that with the existing API so I've added a new function to expose it.
```lua
require("lspsaga.diagnostic").show_cursor_diagnostics()
```
What do you think?
> Add method for diagnostics under the cursor

- lua/lspsaga/codeaction.lua
In
https://github.com/glepnir/lspsaga.nvim/commit/8847e8b91579dd62e325f99f202092953b6793ed
`close_preview()` was removed from diagnostic. So this line is causing:
```
E5108: Error executing lua ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:86: attempt to call field 'close_preview' (a nil value
)
```
when someone tries to do a code action now.
> Fix nil error when attempting code action.

- lua/lspsaga/signaturehelp.lua
that pr fixes check for signature_help when `efm` is used ( previously if there `efm` first lsp it returned `false` which is not always correct )
> fix signaturehelp

- lua/lspsaga/provider.lua
the current implementation fails when there is multiple results
current result array
```lua
{
{
result = {}
},
{
result = {
{
range = {
end = {
character = 20,
line = 42
},
start = {
character = 12,
line = 42
}
},
uri = "file:///<path>/app/node_modules/next/types/index.d.ts"
}
}
}
}
```
after PR
```pr
{
{
result = {
{
range = {
end = {
character = 20,
line = 42
},
start = {
character = 12,
line = 42
}
},
uri = "file:///home/ashraf/projects/veve/app/node_modules/next/types/index.d.ts"
}
}
}
}
```
> fix: review_definition with multiple servers

- lua/lspsaga/command.lua
- lua/lspsaga/diagnostic.lua
If I try render the hover window with `render_hover_doc`, `show_cursor_diagnostics` immediately dismisses the hover doc and render the diagnostics again (happens with `show_line_diagnostics` too). I _think_ this is due to `CursorHold` triggering after `render_hover_doc` which I have bound to show cursor diagnostics
```lua
vim.api.nvim_command('autocmd CursorHold <buffer> lua require("lspsaga.diagnostic").show_cursor_diagnostics()')
```
I've added a check to see if hover doc is present before rendering the diagnostic and provided a way to override it if the function is bound to something else.
> Fix diagnostics conflicting with hover doc

- README.md
This relates to #142 , @glepnir I think you need the `:<C-U>` rather than a `<Cmd>` for this to work. The example you changed it too still didn't work form me but this does
> Fix visual mapping for code action range

- README.md
@glepnir I noticed that this function was added in a recent PR but is not in the README. It's actually quite helpful depending on your preference especially if used for an autocommand, so I've added it
> Add show_cursor_diagnostics to README

- lua/lspsaga/diagnostic.lua
I don't _think_ the [`opts.severity_sort`](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/diagnostic.lua#L69) was doing anything so I've made it do what I think it should - happy to change it though
> Apply severity sorting to all diagnostics before rendering

- lua/lspsaga/window.lua
Explicit title. The function broke with latest changes, simply changing `create_float_contents` to `create_win_with_border` fixes the issue.
> fix open_shadow_float_win

- plugin/lspsaga.vim
Fixed to not overwrite `NormalFloat` if it has already been defined.
> fix: not overwrite NormalFloat

- README.md
- lua/lspsaga/window.lua
- plugin/lspsaga.vim
Added a highlight to be used for the floating window `Normal` used in lspsaga.
I named it `LspFloatWinNormal` to match the highlight name of `LspFloatWinBorder`.
If you don't like it, please let me know. I will fix it.
Refer #180, #183
> feat: add hi LspFloatWinNormal (close #183)

- lua/lspsaga/window.lua
I'm using a simple helper function to show the signature help for a function while I am typing within it. The problem is that the completion menu will be placed over the floating signature help. A simple fix for this is to just detect if the popup menu is visible and set the anchor accordingly.
> feat(window): avoid pmenu

- lua/lspsaga/diagnostic.lua
This change should make `:Lspsaga diagnostic()` work properly
> Fixed deprecated function

- lua/lspsaga/codeaction.lua
When using the unstable branch of neovim, the autocmd CursorHold (on init.lua) was emitting an error when a server that didn't had the capability of code action. 
I added a function that checks if there was a client with the codeAction capability, and used it on other functions that emitted codeAction.
> Disabled action when no support

- lua/lspsaga/provider.lua
Related to #128 
I found in my TypeScript code that `definition_preview` is intermittently broken producing the below error.
```
E5108: Error executing lua vim/shared.lua:219: after the second argument: expected table, got nil                                                                                                                                               
stack traceback:                                                                                                                                                                                                                                
vim/shared.lua:219: in function 'tbl_deep_extend' …
```
> Fix preview_definition when definition comes from server ID 2

- lua/lspsaga/window.lua
Just a simple find-and-replace.
> refactor: correct typo ("wraped" -> "wrapped")

- lua/lspsaga/codeaction.lua
Change the texthl argument for the lightbulb sign from `LspSagaLightBulbSign` to `LspSagaLightBub` so that it match the default highlight group definition in `plugin/lspsaga.vim`.
> Fix a mismatch of lightbulb highlight group name

- README.md
- lua/lspsaga/init.lua
- lua/lspsaga/rename.lua
- lua/lspsaga/symbol.lua
- lua/lspsaga/window.lua
- plugin/lspsaga.lua
use normal buffer instead of prompt-buffer. in normal buffer we can into visual mode ,I think this is useful . and there has a new option `rename_into_visual` default is true. if set false. won't into visual mode in rename window. remove `rename_prmpt_prefix` option.
> Improve rename

- lua/lspsaga/window.lua
When I use work for tsx/jsx, if I meet a error and I press <leader>j(which is map to command `:Lspsaga diagnostic_jump_prev`). It will throw a error message(connot contains newlines).
With debug print,I found that `typescript-language-server` will response to a message which the line maybe contains `\n` special character and `nvim_buf_set_lines` api not allow a string contains `\n`character.
before this commit:
after this commit:
> fix content with newlines

- lua/lspsaga/codeaction.lua
- lua/lspsaga/definition.lua
- lua/lspsaga/finder.lua
- lua/lspsaga/init.lua
- lua/lspsaga/libs.lua
- lua/lspsaga/rename.lua
autocmd created by `nvim_create_autocmd` using a lua function doesn't have a good string representation:
if you want to know what autocmds you have in an event, like `:autocmd CursorHoldI`,
you will only see a `lua function`, this makes debugging becomes much more difficult if you have some unexpected behavior which might comes from autocmd, if autocmd comes from an anonymous group, this thing becomes worse: you completely have no idea where this autocmd comes from and don't know how to debug.
I add augroup for all the autocmd created by `lspsaga` to mitigate this kind of issues as it is at least better than an anonymous group.
> Add augroup for autocmd created by lspsaga

- lua/lspsaga/floaterm.lua
After #289, the `close_float_terminal` function only closes the floating window, not the shadow window.
> Fix `close_float_terminal`

- lua/lspsaga/libs.lua
Well, I think it should be added back, because:
1. as a vimmer, when I see a block cusor, that mean I am in normal mode, so I will try to move up and down with `jk` first time.
2. in some way, \<C-n> and \<C-p> trully a  idiom usage to move up and down in vim but only in insert mode, because single input will input character, since now we are in normal mode, there would be no need to input composite keys, that why `vim model` is a awesome concept because it reduce our input complexity.
also, I banned more motion according to your origin idea
> make jk useabe and ban more motion

- lua/lspsaga/symbolwinbar.lua
> fix: typo on `vim.notify` causing error

- lua/lspsaga/symbolwinbar.lua
I think `(left + right) >> 1` is better here
`#a > 0` is likely optimized by luajit but optimizing it doesn't make the code uglier so might as well...
> refactor(symbolwinbar): Minor performance improvement

- plugin/lspsaga.lua
Provide the `default` option when highlight is set.
Currently `lspsaga.nvim` overwrites all highlight groups after the initialization, this change allows colorscheme providers to change the colors
```
The [default] argument is used for setting the default highlighting for a
group.	If highlighting has already been specified for the group the command
will be ignored.  Also when there is an existing link.
```
> fix: allow to overwrite highlight groups 

- lua/lspsaga/lightbulb.lua
I was getting an annoying error when no servers supported codeactions on the current buffer(#268, #259)
"Error detected while processing CursorHold Autocommands for "*":                     
method textDocument/codeAction is not supported by any of the servers registered for the current buffer"
This seems to have fixed it.
> Fixes check for code action support

- README.md
- lua/lspsaga/diagnostic.lua
Main goal is for users to be able to jump only to errors (ignoring warnings, hints, etc.). We might want to create commands for these as well? Something like `goto_prev_error`?
> feat(diagnostic): goto_* functions accept options

- README.md
- lua/lspsaga/definition.lua
- lua/lspsaga/implement.lua
- lua/lspsaga/symbolwinbar.lua
- lua/lspsaga/window.lua
Also, the current winbar behavior is not very good
If `vim.wo.winbar = nil` then it will not remove the extra one line. However `vim.wo.winbar = ""` does... Upstream bug?
https://user-images.githubusercontent.com/56817415/177960834-8f1efa04-cb42-4dc7-b179-5fff209687ec.mp4
in_custom manage to overcome this because I pattern matching every buffer
https://user-images.githubusercontent.com/56817415/177961447-5c8a2106-57df-4712-b3b6-4facdac0c218.mp4
> fix(symbolwinbar): Extra space on non-icon buffer

- lua/lspsaga/definition.lua
`split_by_pathsep` can't be found after https://github.com/glepnir/lspsaga.nvim/commit/9922e17c8e535328462fa246cc8fde32d9f72371, so update definition.lua as well.
> fix split_by_pathsep

- lua/lspsaga/outline.lua
```lua
local saga = require('lspsaga')
saga.init_lsp_saga({
symbol_in_winbar = {
enable = true,
},
show_outline = {
win_position = 'left',
}
})
```
When I use this config, left split will generate new window.
> fix left split

- README.md
According to this: https://neovim.discourse.group/t/which-one-has-more-precedence-noremap-or-remap/2526/2
`vim.keymap.set()` ignores `noremap`. It overrides `noremap` based on the value of `remap`, which is false by default, so there is no need to specify that.
> fix: remove `noremap` option from mappings

- lua/lspsaga/window.lua
Fix hover for `objective-c/objective-cpp`. And sometimes `clang/ccls` also recognizes c/cpp files as objc/objcpp files, this pr also fixes it. 
Before
After
> Fix hover for objective-c/objective-cpp

- lua/lspsaga/init.lua
- lua/lspsaga/lspkind.lua
`custom_kind` would only be respected when symbols in winbar is enabled:
https://github.com/glepnir/lspsaga.nvim/blob/b59ff0d1752f7e9ef93363b71a2cd9b8f2011fec/lua/lspsaga/init.lua#L105-L108
Where `require('lspsaga.lspkind').gen_symbol_winbar_hi()` modified lspkind icons.
`custom_kind` would overwrite icons / colors in any occasion.
Handle the `custom_kind` table separately.
> fix(kind): `custom_kind` wouldn't take effect in some occasions.

- README.md
- lua/lspsaga/codeaction.lua
- lua/lspsaga/init.lua
- lua/lspsaga/lightbulb.lua
This can improve code action speed. new option
`cache_code_action` default is true.  disable it will not cache the code action.
> feat: cache code action in lightbulb

- README.md
The example config had the mappings for jumping to the next error and previous error interchanged.
> fix mapping in example config for error jumping

- README.md
- lua/lspsaga/codeaction.lua
- lua/lspsaga/command.lua
- lua/lspsaga/definition.lua
- lua/lspsaga/diagnostic.lua
- lua/lspsaga/finder.lua
- lua/lspsaga/init.lua
- lua/lspsaga/outline.lua
- lua/lspsaga/symbolwinbar.lua
- plugin/lspsaga.lua
- fix symbolwinbar high memory usage
- `preview_definition` chang to `peek_definition` support edit definition file in floatwindow and highlight
- `code_action` support in visual mode .
- `finder` preview highlight current word.
-  show diagnostic source by default.
- add lspsaga codeaction keymap in diagnostic header
-  remove `definition_preview_icon`  option
- remove `finder_preview_hl_ns`
- remove `diagnostic_source_bracket`
- remove `show_diagnostic_source` .
> Version 2.2

- lua/lspsaga/definition.lua
1. Peeking definitions within the same buffer
2. Peeking definitions across buffers/files
3. edit/split/vsplit/tabe
https://user-images.githubusercontent.com/12182069/190087724-c065774a-b551-4e40-8a79-c1e7315e716f.mov
> fix(definition): support peeking multiple definitions

- .github/workflows/ci.yml
This commit fixed the problem with formatting CI. Currently incorrect artifact was chosen due to the introduction of `linux-aarch64` artifacts of latest `stylua-action` _(a.k.a, `v1.1.0`)_, which would cause "ELF not found" related errors.
> Ref: https://github.com/JohnnyMorganz/stylua-action/releases/tag/v1.1.1
> fix(CI): Broken workflow (ELF not found).

- lua/lspsaga/symbolwinbar.lua
This `if not config.click_support then` branch is skipped when `click_support` is not false or nil as anything not false or nil is true
> fix: winbar click_support always not invoked when as function

- lua/lspsaga/rename.lua
If the treesitter parser is not installed, return true directly.
> fix: fix rename bug

- README.md
- lua/lspsaga/symbolwinbar.lua
It's convenient to custom winbar filename with custom file formatter.
When set file_formatter to `%:.`, it will expand to:
> Support custom winbar filename

- lua/lspsaga/definition.lua
Since the `focus_last_window` function was placed above the `close_window` function call at https://github.com/glepnir/lspsaga.nvim/commit/580c04f13413b6d23a2defe1320afaf521079d45, the `last_window` is now not the correct window to focus.
https://user-images.githubusercontent.com/12182069/194703469-32f11088-298b-49ea-b0fd-69f9403a4c82.mov
https://user-images.githubusercontent.com/12182069/194703480-e85da2a1-d707-4cf5-8291-657a71d4db88.mov
> fix(definition): fix preview windows going back issue

- lua/lspsaga/definition.lua
Unset the `main_winid` (introduced in https://github.com/glepnir/lspsaga.nvim/commit/580c04f13413b6d23a2defe1320afaf521079d45) when all the definition windows are closed.
> fix(definition): unset the main_winid

- lua/lspsaga/diagnostic.lua
> add diagnostic code in diagnostic window

- lua/lspsaga/diagnostic.lua
Before this commit, if the entry source was missing then the diagnostic view would fail with:
```
Error executing Lua callback: ...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/diagnostic.lua:57: attempt to concatenate field 'source' (a nil value) stack traceback:
...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/diagnostic.lua:57: in function 'render_diagnostic_window'
...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/diagnostic.lua:226: in function 'move_cursor'
...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/diagnostic.lua:234: in function <...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/diagnostic.lua:229>
.../share/nvim/plugged/lspsaga.nvim/lua/lspsaga/command.lua:56: in function 'load_command'
...local/share/nvim/plugged/lspsaga.nvim/plugin/lspsaga.lua:83: in function …
```
> Only append entry source and code where available

- README.md
- lua/lspsaga/finder.lua
- lua/lspsaga/init.lua
- lua/lspsaga/libs.lua
finder_action_keys mappings including 'vsplit', 'split', and 'tabe', etc.
should support multiple key choices as 'open' and 'quit' already do.
In addition, we add sensible default keys <CR> and <ESC> as default
keymappings to 'open' and 'quit' actions, respectively.
> fix: Allow multiple keys for finder_action_keys mapping

- lua/lspsaga/finder.lua
When first line is empty at -preview_lines_above, `nvim_buf_add_highlight` don't works because of `vim.lsp.util._trim` 
example) preview_lines_above = 3, find symbol: DIRE
actual lines
```
(empty line)
haha
DIRE
```
preview window
```
haha
DIRE
```
> FIX: no match highlight word, because trim of lsp

- lua/lspsaga/command.lua
- plugin/lspsaga.lua
1. deprecate LSoutlineToggle, use Lspsaga outline instead
2. remove deprecated command preview_definition & range_code_action
> deprecate LSoutlineToggle, remove previous deprecated commands

- lua/lspsaga/command.lua
Hi there 👋 
5ff2bc5935 fixed a typo made on the `goto_definition` function call but there is still _another_ typo when requiring the function causing the following error:
```
Error executing Lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:11: attempt to call method 'goto_defintion' (a nil value)
stack traceback:
...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:11: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:10>
...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'
...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:7>
```
This small commit addresses that issue 😊
> fix goto_definition remaining typo

- lua/lspsaga/hover.lua
Some LSP servers return `textDocument/hover` contents as a markdown string (e.g. typescript-language-server)
Therefore, if the contents is a string, modify it to the appropriate type.
> Fix hover_doc failure

- lua/lspsaga/hover.lua
[This commit](https://github.com/glepnir/lspsaga.nvim/commit/80980b627918b1d85e465d65a9419fa01b8decc0) changes `&nbsp;` to whitespace but didn't clear the ending `;`, so clear it as well
Additionally, substitute/escape `&lt;` and `&gt;` 
[Example file](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/__init__.py), pressing hover on this file is currently showing `<` as `&lt;`
> Escape more characters

- lua/lspsaga/codeaction.lua
support table for keys as in finder, i.e.
```lua
code_action = {
keys = {
quit = { 'q', '<Esc>' },
},
},
```
> feat(codeaction): support table for keys

- lua/lspsaga/symbolwinbar.lua
When `respect_root = true`, there will be an error due to wrong type of parameter.
> Fix the error when `respect_root = true`

- lua/lspsaga/highlight.lua
Related: https://github.com/catppuccin/nvim/issues/386
> fix(highlight): CodeActionText doesn't use colors table

- README.md
There is a typo in the `README.md`: "flaotwindow" instead of "float window"
> docs: correct typo

- README.md
Fix typo with an error in the install section for lazy package manager
> docs(README): typo in the lazy section

- lua/lspsaga/codeaction.lua
- lua/lspsaga/diagnostic.lua
- lua/lspsaga/hover.lua
This PR sets the `foldlevel` to the highest fold number of markdown fold headings when creating a floating window.
This should fix an interference when e.g., using https://github.com/preservim/vim-markdown with heading auto folding enabled.
Experienced issue: In my case, I have set headings above level 4 to auto-fold. Normally this should not trigger folding of content for lspsaga, but still floating windows of lspsaga were opened with folded content.
Besides the mentioned plugin it will in general prevent content being opened folded in sagas floating windows.
It was already fixed once before the lspsaga 2.3 refactor in #26 . But setting the `foldlevel` when creating the window got lost along the way.
> fix floats opens folded

- lua/lspsaga/diagnostic.lua
I don't use text for sign column to keep the number column neat and tidy. But that will cause lspsaga panic when I invoke the cursor diagnostic action.
This PR check `sign.text` is not nil before getting its length. When the `sign.text` variable is nil, it will default use `1` as col_end value.
> fix: add default value when sign text is nil

- README.md
- lua/lspsaga/definition.lua
- lua/lspsaga/diagnostic.lua
- lua/lspsaga/finder.lua
- lua/lspsaga/highlight.lua
- lua/lspsaga/init.lua
- lua/lspsaga/symbolwinbar.lua
- plugin/lspsaga.lua
- Preview
now finder preview window is a normal buffer that support edit file save.  use new option `finder.keys.jump_to` to jump into it then do your edit.
- Highlight
syntax  highlight for nvim 0.9 use treesitter render for nvim 0.8 use regex syntax highlight.  why it different. because when you are in a huge project.  the lsp request of `textDocument/definition textDocument/reference textDocument/implement`
will have lots of responses . these responses will have many file link that need convert to buffer.   when buffer load it will trigger `FileType` event. currently lspconfig use `FileType` event to attach buffer to lsp client. if the server not support 
`workspaceFolder` it will spawn many lsp server instances and more memory usage .  make finder very slow. that's too bad. so I …
> version 2.3.6

- README.md
- doc/lspsaga.nvim.txt
- lua/lspsaga/codeaction.lua
- lua/lspsaga/init.lua
This is useful if you have many active LSPs. Won't be useful for everyone though which is why i've set it to be disabled by default.
> Option to show name of the LSP in code actions

- lua/lspsaga/codeaction.lua
- lua/lspsaga/diagnostic.lua
This commit ensures non-alphanumeric characters _(except white spaces)_ can be matched when getting the exec number for `codeaction`. It is useful when `codeaction` prompts are not in English / The prompt returned by a language server does not start with an alphanumeric character.
It produces the following results in the test buffer:
| LineNr                            |  Stat      |
|---------------------------------|:------:|
| Line 1 (zh)                     |   **OK**   |
| Line 2 (ja)                     |   **OK**   |
| Line 3 (en)                     |   **OK**   |
| Line 4 (no message)             | **FAILED** |
| Line 5 (still a valid response) |   **OK**   |
| Line 6 (nothing)                | **FAILED** |
> fix(codeaction): Match non-space characters

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/codeaction.lua
- lua/lspsaga/definition.lua
- lua/lspsaga/diagnostic.lua
- lua/lspsaga/finder.lua
- lua/lspsaga/lspkind.lua
- lua/lspsaga/outline.lua
I went through and just fixed any grammatical errors I noticed. This includes things like, "Sorry does not any Definition Found" in the attached screenshot. (Love your work by the way!)
> Fix some grammar in messages/errors

- lua/lspsaga/diagnostic.lua
When LSP signs are disabled `vim.diagnostic.config({ signs = false })`, calling `:Lspasaga show_cursor_diagnostics` produces the following error
```
Error executing Lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/diagnostic.lua:496: attempt to index local 'sign' (a nil value)
```
When checking the source I noticed that when signs are disabled calling `vim.fn.sign_getdefined` returns an empty list.
Note: formatting was applied by my LSP suneko Lua server
> fix: error when showing diagnostic if lsp signs are disabled

- lua/lspsaga/hover.lua
I got error if no information is available on hover.
```
Error executing vim.schedule lua callback: ...s/github.com/glepnir/lspsaga.nvim/lua/lspsaga/window.lua:339: attempt to compa
re number with nil
stack traceback:
...s/github.com/glepnir/lspsaga.nvim/lua/lspsaga/window.lua:339: in function 'win_height_increase'
...os/github.com/glepnir/lspsaga.nvim/lua/lspsaga/hover.lua:73: in function 'open_floating_preview'
...os/github.com/glepnir/lspsaga.nvim/lua/lspsaga/hover.lua:213: in function 'handler'
...r/neovim/HEAD-42d5142/share/nvim/runtime/lua/vim/lsp.lua:1391: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
> fix: error when calling hover if no information available

- README.md
- doc/lspsaga.nvim.txt
- lua/lspsaga/command.lua
- lua/lspsaga/definition.lua
Cf issue #850 
* Adding go to type definition functionality mimicking the go to definition implementation.
* Updating the docs with the relevant information to inform on the feature.
Happy to make any changes in the docs or code, I wasn't able to reproduce the same theme as the other showcase so decided against adding an image for the sake of uniformity of style in the docs.
> Adding go to type definition functionality

- lua/lspsaga/definition.lua
The current state of lspsaga doesn't work with nightly neovim version, this change should fix that
> definition: fix typo

- lua/lspsaga/diagnostic.lua
I experienced the same error/a similar error as mentioned in #754.
I noticed that it only happened on certain numbers (specifically the number of the last code action as it turned out).
I tracked it down to the deletion loop.
I think the problem was that at the time the loop was introduced (a1188f2) there was more text added to `contents`.
But if I am not mistaken the proposed implementation will delete exactly as many mappings as there were created because it takes the length from the same list.
---
And a huge thank you for the great plugin glepnir!!
> diagnostic: Take amount of num_shortcuts to delete from same list as they were created with

- README.md
- lua/lspsaga/finder.lua
- lua/lspsaga/init.lua
The finder window in `lspsaga.nvim` is often too small to display its content, because its size is calculated as the minimum of the content size (proportional to a number of references) and the maximum size from the configuration. This can be a problem when the number of references is too small because it leads to a small preview window.
I've added a new configuration option, `finder.force_max_height`, that allows the user to force the window to the maximum size, even if the content is smaller. This can be useful when the content is smaller than the maximum size, but the user still wants to maximize the window to make it easier to read.
The `finder.force_max_height option` is a boolean value that defaults to false. When set to true, it will force the finder window to the maximum size …
> fix small finder windows

- lua/lspsaga/diagnostic.lua
- lua/lspsaga/libs.lua
Love the new release!
I stumbled upon the following error jumping to a diagnostic (`:Lspsaga diagnostic_jump_prev`) when none of the LSPs support code actions:
```
method textDocument/codeAction is not supported by any of the servers registered for the current buffer
```
I tracked it to this line:
https://github.com/glepnir/lspsaga.nvim/blob/688a3d835a4533ebd2c1ebb7e7c22d53385975d5/lua/lspsaga/codeaction.lua#L163
Looking at other parts of your code, it looks like it's fallible and you had a check for it. For example, `send_request()` has a similar call:
https://github.com/glepnir/lspsaga.nvim/blob/688a3d835a4533ebd2c1ebb7e7c22d53385975d5/lua/lspsaga/lightbulb.lua#L112
And it has the following check before it gets called:
https://github.com/glepnir/lspsaga.nvim/blob/688a3d835a4533ebd2c1ebb7 …
> Check if any servers support code actions in diagnostics

- README.md
- lua/lspsaga/showdiag.lua
Hey, it looks like ++unfocus flag is not respected right now.  I've a one minor question out of topic. Will you add `Lspsaga show_cursor_dignostics` back. I was using it a lot and my workflow has broken after the last update here is the my work around for now.
```
lua require('lspsaga.showdiag'):show_diagnostics({ cursor = true, arg = '++unfocus' })
```
> fix ++unfocus arg

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/showdiag.lua
Currently, `config.ui.title` is not respected for diagnostics.
For example, `Lspsaga show_line_diagnostics` shows a `Line` title.
This PR fixes that, as well as makes the version/config.ui.title check ordering consistent in `callhierarchy.lua` where it was reversed.
> fix: make showdiag respect config.ui.title

- README.md
Clarify the usage of `.setup` with non-empty options in the readme
> docs: clarify usage of .setup() options

- lua/lspsaga/definition.lua
I noticed that keymaps for `peek_definition` do not work at all. This PR should fix that.
> fix: peek_definition mappings

- lua/lspsaga/definition.lua
- lua/lspsaga/hover.lua
Currently, if there are two lsp clients that may report supporting `textDocument/hover`, and one of them "fails" the hover while the other succeeds, a hover will popup **and** "No information available" will be notified.
This PR makes it so that "No information available" is only notified if all the possible clients have have also failed.
(Note: I didn't use `lsp.buf_request_all` because that doesn't pass the `ctx` object to the callback, which is currently used)
Example:
The two servers that are being activated are `tsserver` and `tailwindcss`. Tailwindcss will only hover in cases where you're hovering over a tailwindcss class, so it makes sense that it returning `nil` for the response.
This PR doesn't address that two clients returning non-null values may overlap/have a race condition - …
> fix: any hover client succeeding suppresses 'No information available'

- lua/lspsaga/callhierarchy.lua
When executing `:Lspsaga outgoing_calls` for a java method, and when the cursor is positioned on a node that is outside of the project scope, an error occurs since the preview buffer is not being loaded correctly:
>Error executing lua callback: .../nvim/plugged/lspsaga.nvim/lua/lspsaga/callhierarchy.lua:522: Cursor position outside buffer stack traceback:
E.g., for `CountDownLatch.class` the node url is:
> jdt://contents/java.base/java.util.concurrent/CountDownLatch.class?=jdt.ls-java-project/%5C/Users%5C/anton%5C/.sdkman%5C/candidates%5C/java%5C/19.0.2-amzn%5C/lib%5C/
jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/19%5C/docs%5C/api%5C/=/%3Cjava.util.concurrent(CountDownLatch.class
and its preview cannot be loaded correctly.
As a …
> Display preview for outgoing calls only if buffer content is available.

- lua/lspsaga/callhierarchy.lua
When executing `:Lspsaga outgoing_calls` for a java method, the preview for `jdt` based nodes (e.g. class files outside of the project) does not currently work. 
This PR aims to fix the preview of the files using a JDT LS client.
Use a JDT LS client to display the node content when previewing a specific node. The implementation is based on `nvim-jdtls/lua/jdtls.lua`'s `function M.open_classfile(fname)` method. Since `open_classfile` opens the file in the current buffer, I had to provide a separate method, which uses an already created buffer.  
Ultimately, the `load_jdt_preview` function should be part of the https://github.com/mfussenegger/nvim-jdtls plugin. Once such a method is available there, we can drop the `load_jdt_preview` method.
1. Opened a java project.
2. Executed `:Lspsaga …
> #975: Fix JDT previews in "outgoing_calls" popup.

- lua/lspsaga/rename.lua
Currently, if the user has `<esc>` mapped to `rename.quit`, they cannot enter normal mode from either insert or visual mode. Instead, pressing `<esc>` closes the window.
> Don't map <esc> to quit in renaming unless it's normal mode

- lua/lspsaga/hover.lua
If hover_doc is executed once in a buffer that does not support Hover, hover_doc becomes unusable afterwards.
In this case, the following message is displayed:
```
[Lspsaga] There is already a hover request, please wait for the response.
```
This issue has been fixed.
> Fix issue with hover_doc becoming unusable

- lua/lspsaga/callhierarchy.lua
When using `Lspsaga outgoing_calls`, the methods being called from a specific method get displayed in the list on the left side. In order to identify which class the respective method belongs to, we have to move the cursor to the line and see the name of the class in the preview window on the right. It would be more convenient if we can see all the target classes that the methods belong to at a glance.
Add the name of the class that the respective method in the preview belongs to using a ' @ <shortClassName>' suffix.
When the class is the same as the class the method was called, the shortClassName will be empty and the suffix would be ' @'.
Before change, executed `Lspsaga outgoing_calls`:
After change, executed `Lspsaga outgoing_calls`:
We can see that the class names are present with …
> Show classname of outgoing call in preview.

- lua/lspsaga/lspkind.lua
There was a missing space for the `function` symbol.
It could make sense to wrap them all into a function that adds the extra space or any pre/suffix
> style: function symbol missing space

- lua/lspsaga/definition.lua
If go to definition happen on the same buffer, the `edit` command will close and enter the current buffer. That will hurt some REPL plugin (like https://github.com/kiyoon/jupynium.nvim) as it missunderstand you are quitting nvim.
This will resolve https://github.com/nvimdev/lspsaga.nvim/issues/1032
> chore(definition): do not enter current buffer

- lua/lspsaga/callhierarchy.lua
Some class names are not visible in `Lspsaga outgoing_calls` for methods which reside in classes, referenced in the project itself, i.e. by java source instead of by class file. We need to enhance the capturing of the class name in the preview window. 
The current code handles properly urls, which are:
>jdt://contents/slf4j-api-1.7.30.jar/org.slf4j/Logger.class?=server/%5C/Users%5C/user%5C/.m2%5C/repository%5C/org%5C/slf4j%5C/slf4j-api%5C/1.7.30%5C/slf4j-api-1.7.30.jar=/gradle_used_by_scope=/integrationTest,main,test=/%3Corg.slf4j(Logger.class
but the following urls are not handled properly:
>file:///Users/user/source/atlas/cloud-services-agents/vsphere-inventory-agent/server/src/main/java/com/company/product/cloud/inventory/monitor/MonitorRegistry.java
Enhance the regular expression for …
> Fix project class names in outgoing calls preview.

- lua/lspsaga/finder.lua
Currently it is not possible to navigate up with cursor to the first entry of the finder. This small change fixes the bug.
before:
after:
> fix: finder cursor navigation

- lua/lspsaga/finder.lua
the displayed virtual text is usefull in a couple of cases: 
1) emphasise current line, sometimes it is a bit difficult to detect current line in the finder window 
2) keep track of current idx and overall count of text occurences inside buffer
> feat: virtual text along with word highlight for reference node

- lua/lspsaga/finder/init.lua
- lua/lspsaga/util.lua
- test/util_spec.lua
Call ":Lspsaga finder" at a dumb position will cause lspsaga stuck.
In this case, result given by lsp is like {{}}
> fix empty result in finder

- lua/lspsaga/finder/init.lua
Turns out that after calling `nvim_win_set_buf` for a window, all local options will be overwritten. Wrote a fix to restore the original winhl after `nvim_win_set_buf`.
> fix(finder): restore winhl after buffer changes

- lua/lspsaga/diagnostic/init.lua
- lua/lspsaga/diagnostic/show.lua
The indexes of rows and columns are different from the actual ones：
When the mouse is behind the cursor, diagnostic should not be displayed：
Originally:
https://github.com/nvimdev/lspsaga.nvim/assets/92523839/585e0278-4cbe-4572-a040-f055df71d2de
After repair:
https://github.com/nvimdev/lspsaga.nvim/assets/92523839/bde3d271-7b1c-4c29-a7a1-7452946f6996
> fix index of diagnostic

- lua/lspsaga/rename/init.lua
With 95ec55d I'm getting the following error when trying to rename a struct member in C:
```
E5108: Error executing lua: ...share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename/init.lua:82: bad argument #1 to 'ipairs' (table expected, got nil)                                    
stack traceback:                                                                                                                                                                     
[C]: in function 'ipairs'                                                                                                                                                    
...share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename/init.lua:82: in function 'parse_arugment' …
```
> Fix exception with lsp_rename()

- lua/lspsaga/definition.lua
This is the follow-up work for this https://github.com/nvimdev/lspsaga.nvim/pull/1074, as the latest update has rendered the previous changes ineffective.
> chore: do not edit current bufnr

- lua/lspsaga/util.lua
- test/util_spec.lua
I noticed that finder window doesn't display path to the file correctly, sometimes in displays full path, which is no pleasant.
It turns out that the special characters in root path should be escaped with "%" https://www.reddit.com/r/lua/comments/jnoytk/comment/gb5dnkk/?utm_source=share&utm_medium=web2x&context=3
Thus, it is needed to handle special characters and convert root path string to pattern string by escaping special characters with "%"
> finder: fix root path trim

- lua/lspsaga/codeaction/init.lua
It looks nicer to have a space between the 2 words 😄
> Add space to code action title

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/definition.lua
- lua/lspsaga/diagnostic/init.lua
- lua/lspsaga/finder/box.lua
- lua/lspsaga/finder/init.lua
- lua/lspsaga/hover.lua
- lua/lspsaga/lspkind.lua
- lua/lspsaga/rename/init.lua
- lua/lspsaga/rename/project.lua
- lua/lspsaga/symbol/outline.lua
This PR submits fixes I found grepping through lspsagas notifications.
I got there after encountering spelling problems with some of the error messages I'm seeing lately.
It mainly fixes typos and phrasing. Also, the messages were made uniform. E.g. as prefix `[lspsaga]` `[lspsaga.nvim]` and `[Lspsaga]` was used - here I opted for a unifrom `[lspsaga]`. Please let me know if changes are desired.
> fix: spelling in notify messages

- lua/lspsaga/symbol/winbar.lua
A fix had previously been made for #1206 (see commit 1a38e4c), however the issue remained when using `get_bar()`  for custom components. This change addresses that use case and has been tested on neovim 0.9 and 0.10.
> fix symbols winbar when using get_bar(). follow up #1206

- lua/lspsaga/diagnostic/init.lua
I want to fix this error.
The error above occurs when I run `:Lspsaga diagnostic_jump_next` with the cursor on a line before the end of the file. 
If entry.col is nil, use 1 as a fallback.
> hotfix: Fall back to 1 when entry.col is nil

- lua/lspsaga/finder/init.lua
_ is a global variable which can be assigned to. In fact, even here the global _ is assigned to:
https://github.com/defr0std/lspsaga.nvim/blob/8365520841a69111b8d7ae47fad5cbf88000885a/lua/lspsaga/finder/init.lua#L39
So the normal finder works just the first time. The second time, the _ variable can contain a bufnr, so the window is not initialized properly.
I also found other installed plugins which set the _ variable to various values such as empty string, empty table, etc.
> do not pass _ as arguments in finder

- lua/lspsaga/finder/init.lua
This is a small convenience improvement. Currently, when the finder uses a normal layout with sp_global, the reference is always open ('toggle_or_open') in the leftmost window. This is quite inconvenient when working with multiple vertical splits. Imagine that you search for reference in the right split, and then the reference is open in the left split, which has a completely different context.
When the finder is open, we memorize the current window id. When the reference is opened, we use that window id instead of 0 (which by this time is already the leftmost).
For float layout, or normal with sp_global=false, there is no change in behavior.
> open finder reference in the calling window

- lua/lspsaga/symbol/outline.lua
This fix address an error being thrown when reopening the outline, and is a follow up to #1304.
The autocommand group `outline` is initialised on line 18 of `outline.lua`.
The `clean_ctx()` function deletes the `outline` group by id (`nvim_del_augroup_by_id`). 
This function is called when closing the outline.
Attempting to reopen the outline causes an error to be thrown, as the autocommand group ID given has been deleted.
This fix recreates the `outline` group in the `outline_normal_win()` and `outline_in_float()` functions, allowing a valid ID to be used when the outline is refreshed.
> fix outline autocommand group issue. follow up #1304

- lua/lspsaga/command.lua
Fixing broken `peek_type_definition` and `goto_type_definition` commands
> fix: `peek_type_definition` and `goto_type_definition` commands

- lua/lspsaga/symbol/outline.lua
Change to current window rather than last window who buffer attach with, original behavior can make unwanted switch to last window in different tab or split window. Make it same behavior with `finder`.
> refactor(outline): change `jump` behavior window

- lua/lspsaga/definition.lua
I was trying to troubleshoot why the peek_definition was not working for `clojure-lsp`.
This message would've been helpful =)
> Fix typo to prevent multiple definition requests

- lua/lspsaga/definition.lua
This was merged before on #1311  but seems to have been lost (rebase, maybe?)
Reopening :)
> Fix typo on definition and set pending_result to false when no result from LSP

- lua/lspsaga/hover.lua
- lua/lspsaga/symbol/winbar.lua
My change was removed. #1067
Added a comment for future reference. 
Before
After
> feat(hover): add syntax highlighting for tailwindcss

- lua/lspsaga/diagnostic/init.lua
I believe this PR will fix issue https://github.com/nvimdev/lspsaga.nvim/issues/1319. When the diagnostic appears in the beginning of line.
> fix: jump to diagnostic with v.col is nil

- lua/lspsaga/util.lua
This PR try to use 'nx' mode for feedkeys to avoid remap keys. So scroll keys won't break with user's mappings.
> Use nx mode to avoid remap keys

- lua/lspsaga/diagnostic/show.lua
- lua/lspsaga/init.lua
Currently, if user uses `vim.opt.wrap = false` in their config and the line is too long, then it is impossible to display the whole diagnostic message.
This PR adds the ability to enable wrap in diagnostic window even though they use `vim.opt.wrap = false` in their config
> feat: add wrap_long_lines option for diagnostic window

- doc/lspsaga.nvim.txt
- lua/lspsaga/diagnostic/show.lua
add a white space betweent diagnostic source and code
fix https://github.com/nvimdev/lspsaga.nvim/issues/1371
> fix: show better diagnostic message

- lua/lspsaga/rename/init.lua
Typo in the method argument. I think it goes unnoticed because nvim lsp just assumes the client supports the method if it can't find it when looking it up. See [here](https://github.com/neovim/neovim/blob/b413f5d048ab8676d5a77d0f2b3c20587a270673/runtime/lua/vim/lsp/client.lua#L860C3-L863C6).
> fix: fix small typo for string used when filtering clients by method

- lua/lspsaga/finder/box.lua
PR should fix #1394. Below is the example in the docs for filtering in the finder. Since it's specified that func should return a bool, I *think* the func is meant to be called on each element of the `result` table rather than the `result` table itself (which itself is just part of the map returned by `vim.lsp.buf_request_all()`; the reuse of names is confusing). This way, I think it's more like the user can write filters that act on the finder results. Correct me if I'm wrong.
Additionally, `fn()` in `box.filter` should also take `client_id` so that filters are applied properly.
If all looks good, I can clean up comments and/or change the name of `result_member` variable to something else.
```lua
require('lspsaga').setup({
finder = {
filter = {
['textDocument/references']  = …
```
> fix: finder filter functions should work on items inside of result table rather than the result table as a whole

- lua/lspsaga/symbol/winbar.lua
Whenever the winbar didnt have any items to show (and it results to only folder/filename), it broke out of the filename highlight group, which with some themes would result in a black bar after the filename.
I noticed it doesn't break the highlight group when it actually does display the cursor's context, so maybe i revealed a bug ¯\_(ツ)_/¯
> Fix winbar.lua highlight when on a blank line.

- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/codeaction/preview.lua
- lua/lspsaga/highlight.lua
- lua/lspsaga/init.lua
I changed the hard coded margin between preview and code actions to make it 0 whenever `ui.border == 'none'`.
I also made a `code_action.cursorline` option defaulting to `true`. This feels like a more sane default since it's more of a 'completion-like' UI.
Let me know if you think it's okay, I will then update docs and other things if required!
https://github.com/nvimdev/lspsaga.nvim/assets/39461169/63bc31f7-1a94-4e80-8654-a9e4f3a45000
https://github.com/nvimdev/lspsaga.nvim/assets/39461169/465ea5c4-927e-4eda-af84-85d6f1bb8249
https://github.com/nvimdev/lspsaga.nvim/assets/39461169/7460e32c-83d2-4e70-af49-e48a1b48fef6
> refactor(codeaction): border margin handling + CodeActionCursorLine highlight

- lua/lspsaga/hover.lua
Now instead of waiting for previous request to complete do a cleanup by calling the cancel function returned by `vim.lsp.buf_request` and proceed to create a new lsp request. Seems to help with both regular hover windows and `++keep` windows. 
Long-term tho it is probably better to use `vim.lsp.buf_request_all` instead of `vim.lsp.buf_request` as by [this nvim issue](https://github.com/neovim/neovim/pull/19738).
> fix(hover): cancel prev lsp hover request on new requests instead of waiting addresses #1417

- lua/lspsaga/diagnostic/init.lua
Closes #1433 
Hello, I made a PR for fix the code action with 'o' in diagnostic context. It's very happy to me if it can be merged.
> fix: execute codeaction with 'o' in diagnostic

- lua/lspsaga/init.lua
- lua/lspsaga/luadoc.lua
1. Fixed a typo (`symbol_in_winbar.dely` --> `delay`)
2. Created luadoc so the LSP can validate your options
- These docs are created from the latest `init.lua`, but using the descriptions from the website
> Fix typo and Create Luadoc

- lua/lspsaga/symbol/winbar.lua
origin pr is https://github.com/nvimdev/lspsaga.nvim/pull/1363, but seems it is missing, so I pr it again
close: https://github.com/nvimdev/lspsaga.nvim/issues/1362
> fix: escape char % is not handled

- lua/lspsaga/codeaction/lightbulb.lua
- lua/lspsaga/init.lua
Ignore some lsp clients or filetypes, the option is the same as https://github.com/kosayoda/nvim-lightbulb
> feat: add lightbulb.ignore options

- lua/lspsaga/hover.lua
I believe the missing parameter was causing #1473
I could be wrong about this being the right fix, but providing the parameter fixed the issue for me.
> fix(#1473): Update hover.lua -- missing lsp.Handler parameter

- lua/lspsaga/symbol/outline.lua
Before:
https://github.com/user-attachments/assets/e55c451d-3286-4bc1-b06f-28e7597561f0
After:
https://github.com/user-attachments/assets/23200acb-7200-4a90-a5b0-476469216a59
> fix(outline): calc width/height for preview win based on columns

- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/codeaction/lightbulb.lua
I fixed this error(`position_encoding param is required in vim.lsp.util.make_range_params. Defaulting to position encoding of the first client.`) that was occurring on nightly.
If using the 'stable release' version, there were no arguments for `make_range_params`, so it was not necessary to branch by version.
ref: https://github.com/neovim/neovim/pull/31249
> fix: Use offset encoding of first client

- lua/lspsaga/codeaction/init.lua
Fixes #1507 
In https://github.com/nvimdev/lspsaga.nvim/pull/1506 the offset was added to `make_given_range_params`, but the signature of the function is:
```lua
function M.make_given_range_params(start_pos, end_pos, bufnr, offset_encoding)
```
Which in servers like `clangd` was causing this issue:
```
Error executing vim.schedule lua callback: .../neovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/util.lua:2074: bufnr: expected number, got string
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
.../neovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/util.lua:2074: in function '_get_offset_encoding'
.../neovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp/util.lua:2148: in function 'make_given_range_params'
...e/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua:178: …
```
> fix: add missing parameter to `make_given_range_params`

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/codeaction/lightbulb.lua
- lua/lspsaga/codeaction/preview.lua
- lua/lspsaga/definition.lua
- lua/lspsaga/finder/init.lua
- lua/lspsaga/hover.lua
- lua/lspsaga/rename/init.lua
- lua/lspsaga/util.lua
Make sure to always pass a offset_encoding to `make_given_range_params` and `make_position_params`. This is now a warning in nvim 11 even though the functionality hasnt changed, so it's backwards compatible.
Also slight refactorting, add util function `get_offset_encoding` with table for filtering how to get it to match new nvim api. This is used everywhere now.
> Nvim11 position encoding fix

- lua/lspsaga/util.lua
Fixes https://github.com/nvimdev/lspsaga.nvim/issues/1514
> fix: vim.validate not compatible with v0.10

- lua/lspsaga/diagnostic/show.lua
This PR attempts to help display diagnostic messages in a more graceful way.
Before, newline characters ('\n') in diagnostic messages were simply stripped out. This PR instead writes them out to a separate line
**Before**
**After**
Ideally, it'd be nice to not display the horizontal lines so it's more clear certain lines are meant to be grouped together but I wasn't entirely sure how to do that.
Open to feedback!
> fix: split diagnostic lines on \n character in floating window

- lua/lspsaga/codeaction/preview.lua
- lua/lspsaga/diagnostic/show.lua
Added a check if `vim.diagnostic.config.severity_sort` is enabled, if so, sort diagnostic msgs in asc severity order.
> Feature: respect `vim.diagnostic.config.severity_sort`

- lua/lspsaga/definition.lua
When using definition in Deno, the following issue occurs:
https://github.com/neovim/neovim/issues/30908
Since it opens a non-existent path as a virtual file, executing the edit command from peek definition attempts to create and open an inappropriate path that includes the cwd, resulting in an error. I have added a process to convert the path appropriately when opening files that start with deno:/. "
> Fix Deno path handling in definition module

- lua/lspsaga/diagnostic/show.lua
Problem:
Diagnostics were not being displayed when the severity_sort option was not enabled in vim.diagnostic.config(). This issue occurred because the generate_list function only called the callback when severity_sort was set to true, leaving the diagnostics unprocessed in the opposite case.
Solution:
The generate_list function has been modified to always call the callback with the generated list, regardless of whether severity_sort is enabled. This ensures that diagnostics are displayed correctly in all scenarios. Additionally, unnecessary return statements were removed since the caller does not use the return value, simplifying the code.
This fix provides a consistent user experience by ensuring diagnostics work as expected, whether sorting by severity is enabled or not.
Fixes #1520
> Fix(diagnostics) not showing when severity_sort is disabled

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/codeaction/lightbulb.lua
- lua/lspsaga/implement/init.lua
- lua/lspsaga/symbol/head.lua
- lua/lspsaga/symbol/init.lua
- lua/lspsaga/typehierarchy.lua
- lua/lspsaga/util.lua
I'm not entirely sure about the expected version compatibility of this plugin, but from latest stable version the use of methods on Lsp.Client (e.g. client.supports_method) is deprecated and should be used as e.g. `client:supports_method`.
> fix(treewide): remove deprecated uses of LSP client methods

- lua/lspsaga/callhierarchy.lua
- lua/lspsaga/codeaction/init.lua
- lua/lspsaga/codeaction/lightbulb.lua
- lua/lspsaga/implement/init.lua
- lua/lspsaga/symbol/head.lua
- lua/lspsaga/symbol/init.lua
- lua/lspsaga/typehierarchy.lua
- lua/lspsaga/util.lua
Reverts nvimdev/lspsaga.nvim#1538
> Revert "fix(treewide): remove deprecated uses of LSP client methods"
