nvimdev/lspsaga.nvim

README.md, lua/lspsaga/handlers.lua, lua/lspsaga/init.lua, lua/lspsaga/window.lua
This PR adds 2 new options to set the max width of hover window and its border style.
=> feat: add option to configure width and border style

README.md, lua/lspsaga/handlers.lua, lua/lspsaga/init.lua, lua/lspsaga/window.lua
follow up of #2, this won't freeze neovim
=> fix: max_hover_width causing neovim to freeze

lua/lspsaga/provider.lua
Fixes: #24
See the commit message for the details.
=> Fix truncation of paths for finder provider

lua/lspsaga/window.lua
=> Open all folds for floating preview windows

lua/lspsaga/codeaction.lua
Make code_action iterage through lsp servers to gather all possible actions and not depend on lsp servers load order ( on server index )
=> Make code_action iterage through all active lsp servers

README.md, lua/lspsaga/init.lua, lua/lspsaga/provider.lua, plugin/lspsaga.vim
=> Use highlight groups to adjust color appearance

README.md, lua/lspsaga/init.lua, lua/lspsaga/provider.lua, plugin/lspsaga.vim
Reverts glepnir/lspsaga.nvim#42
=> Revert "Use highlight groups to adjust color appearance"

lua/lspsaga/provider.lua
async lsp finder enhance for some language servers with very slow performance, close #33
=> async lsp finder

lua/lspsaga/codeaction.lua
@lucax88x  can you test this patch. it return to use `buf_request`
=> use buf_request close #90

lua/lspsaga/signaturehelp.lua, lua/lspsaga/window.lua
https://github.com/neovim/neovim/pull/14207
Fixes #164
=> Move to new _trim since _trim_and_pad no longer exists

README.md, lua/lspsaga/action.lua, lua/lspsaga/codeaction.lua, lua/lspsaga/command.lua, lua/lspsaga/diagnostic.lua, lua/lspsaga/floaterm.lua, lua/lspsaga/hover.lua, lua/lspsaga/implement.lua, lua/lspsaga/init.lua, lua/lspsaga/provider.lua, lua/lspsaga/rename.lua, lua/lspsaga/signaturehelp.lua, lua/lspsaga/window.lua, plugin/lspsaga.vim
refactor window and fix #156 #152 #166 #170
=> improve behavior

README.md
Currently fails trying to pull from `master`.
=> Fix install branch

lua/lspsaga/codeaction.lua, lua/lspsaga/hover.lua, lua/lspsaga/signaturehelp.lua
The signature for LSP handlers has changed, see https://neovim.io/doc/user/lsp.html#lsp-handler
This PR should fix #261
=> Update signature for LSP handlers.

lua/lspsaga/provider.lua, lua/lspsaga/window.lua
=> Fix finder preview window size issues

README.md, plugin/lspsaga.vim
Add missing highlight group to README and remove unused diagnostics highlight groups.
=> Add missing highlight group to README

lua/lspsaga/diagnostic.lua, lua/lspsaga/libs.lua
=> fix: multiple show diagnostics issues

README.md, lua/lspsaga/rename.lua
- fixed rename (undefined highlight group "CursorWord")
- updated rename section of readme.md for changed function name
=> fix: rename

lua/lspsaga/action.lua
Just as you have metioned in #313 ,  I changed `alter` to `...`， tested and worked good
=> add ... param in function action.smart_scroll_with_saga

README.md, lua/lspsaga/finder.lua, lua/lspsaga/init.lua, lua/lspsaga/libs.lua, lua/lspsaga/lightbulb.lua, lua/lspsaga/lspkind.lua, lua/lspsaga/rename.lua, lua/lspsaga/symbolwinbar.lua
support more filetypes and better design with async and cache . default is false .need neovim nightly
- [ x ] Complete
=> feat: fastest show symbols in winbar

lua/lspsaga/action.lua, lua/lspsaga/definition.lua
There should be result[1].result[1] check in defintion.lua, otherwise it may give a nil error
=> Add check for result in definition.lua

plugin/lspsaga.lua
`Lspsaga` command argument auto complete.
=> feat: command complete

lua/lspsaga/symbolwinbar.lua
https://github.com/glepnir/lspsaga.nvim/issues/332
=> fix(symbolwinbar): index a nil value

README.md, lua/lspsaga/init.lua, lua/lspsaga/symbolwinbar.lua
Preview
https://user-images.githubusercontent.com/56817415/177597748-ea1c1355-3d6e-4c06-9ab4-1450d9b051cf.mp4
=> feat(symbolwinbar): Add click support

lua/lspsaga/finder.lua
Closes https://github.com/glepnir/lspsaga.nvim/issues/325
@glepnir Careful about nightly features...
=> fix(finder): winbar nightly

README.md, lua/lspsaga/symbolwinbar.lua
=> Sanitize file names and paths off the special character %

README.md, lua/lspsaga/finder.lua, lua/lspsaga/init.lua, lua/lspsaga/symbolwinbar.lua, lua/lspsaga/window.lua, plugin/lspsaga.lua
improve finder ui and fix #355
=> feat: improve finder ui

README.md, lua/lspsaga/finder.lua, lua/lspsaga/init.lua, lua/lspsaga/libs.lua, lua/lspsaga/outline.lua, lua/lspsaga/rename.lua, lua/lspsaga/symbolwinbar.lua
=> feat: improve outline

README.md, lua/lspsaga/init.lua, lua/lspsaga/lightbulb.lua
if it's flase, lspsaga won't refresh lightbulb sign when you are in insert mode
=> feat(lightbulb): add option `enable_in_insert`

lua/lspsaga/lightbulb.lua
the current buffer may have been changed during coroutine running and that causes an error.
=> fix(lightbulb): use passed in bufnr

README.md, lua/lspsaga/command.lua, lua/lspsaga/finder.lua, lua/lspsaga/init.lua, lua/lspsaga/libs.lua, plugin/lspsaga.lua
=> feat: finder async and add loading bar

README.md, lua/lspsaga/symbolwinbar.lua
Added note for nvim-jdtls users
=> Charlie39 patch 1

lua/lspsaga/libs.lua
function: get_config_lsp_filetypes
add type-check for elements in server_filetype_map
=> feat(libs.lua): support string type in get_config_lsp_filetypes

README.md, lua/lspsaga/definition.lua, lua/lspsaga/init.lua
Fix https://github.com/glepnir/lspsaga.nvim/issues/490
=> Allow quitting preview_definition with custom shortcut

README.md
Mappings link didn't work, so I removed it.
=> Remove Mappings link from README

README.md
ref: https://github.com/glepnir/lspsaga.nvim/pull/501
=> fix incorrect default configuration values

README.md
Remove parameter that no longer exists.
=> Remove finder_preview_hl_ns

README.md
=> Spelling corrections and changes

lua/lspsaga/definition.lua
Fix the window ID conditions in https://github.com/glepnir/lspsaga.nvim/pull/560
=> fix(definition): fix conditions for the window ID to focus

README.md, lua/lspsaga/definition.lua, lua/lspsaga/finder.lua, lua/lspsaga/init.lua
=> ADD: display lines above in lsp_finder

lua/lspsaga/rename.lua
Pretty self-explanatory, allows esc+\<c-c\> to quit
=> added support to pass table to rename_quit_key

lua/lspsaga/hover.lua, lua/lspsaga/init.lua
add config_values to change the mapping of quitting hover docs while inside its window.
=> ADD: config_values for quitting hover docs while inside it

README.md
=> docs: Add <CR>

lua/lspsaga/init.lua
The changed message gets rid of some grammar mistakes and makes it a bit clearer what is expected of the user (migrate to a specific new callable "setup" function)
--- 
Thank you so much for the amazing work you are doing on this plugin, I have been enjoying it for some years now already and I really like the stuff this plugin does!
And thanks for making these huge changes to it now and streamlining the config! I don't entirely agree with the styling of the float windows and their colors (I just like it default as managed by my editor's theme with lines being the same color as my indent-lines and text being a bit less flashy) but you included a nice list of theming options already, so I'll start trying those out :)
winbar seems to work a lot better (even when called through my lualines …
=> Fix some little grammar mistakes in init_lsp_saga

lua/lspsaga/hover.lua
=> fix(hover): the type of item is not always a string

lua/lspsaga/hover.lua
I'm sorry.
I've taken a few more considerations into account and sorted it out.
Related PR;
#674
#685
=> fix(hover): use the correct types

README.md, lua/lspsaga/init.lua, lua/lspsaga/outline.lua, lua/lspsaga/rename.lua
=> feat: support project level rename

lua/lspsaga/init.lua
=> Fix minor spelling mistake

README.md
I was reading the README and found some typos, so I fixed them.
=> fix(doc): some typos

lua/lspsaga/hover.lua
Related: #674 #688
Fixed an error in tsserver due to incorrectly positioned code for converting contents.
=> Fix hover_doc

README.md
=> fix/Readme: typo

README.md
Corrected a lot of the grammar and spelling mistakes in the README and rewrote a large portion of it to be more easily understood by people.
=> Made the README more readable

README.md, doc/lspsaga.nvim.txt, lua/lspsaga/callhierarchy.lua, lua/lspsaga/codeaction.lua, lua/lspsaga/definition.lua, lua/lspsaga/diagnostic.lua, lua/lspsaga/finder.lua, lua/lspsaga/highlight.lua, lua/lspsaga/hover.lua, lua/lspsaga/init.lua, lua/lspsaga/libs.lua, lua/lspsaga/lspkind.lua, lua/lspsaga/outline.lua, lua/lspsaga/rename.lua, lua/lspsaga/symbolwinbar.lua, lua/lspsaga/window.lua
=> version 0.2.4

lua/lspsaga/callhierarchy.lua, lua/lspsaga/command.lua
=>  improve callhierarchy

lua/lspsaga/definition.lua
From https://github.com/glepnir/lspsaga.nvim/discussions/857
Context:
I have a `BufWritePre` autocmd that formats the current buffer on save.
When using goto-definition, lspsaga was writing the current buffer which caused my autocmd to run and make the jump feel slow.
Solution:
I have added conditions around the write so that it only writes if we are jumping to a location in the current buffer.
=> On goto-definition only write the current buffer if it is modified and the jump destination

README.md
=> typo: add comma

lua/lspsaga/codeaction.lua
=> fix the code action not execute selected options issue

README.md, lua/lspsaga/definition.lua, lua/lspsaga/highlight.lua, lua/lspsaga/init.lua, lua/lspsaga/window.lua
remove `close back next` keymaps in peek_definition.  if you want go back prev definition just `<C-o>` .
=> refactor peek_definition more  easy to use and more useful

lua/lspsaga/diagnostic.lua, lua/lspsaga/highlight.lua, lua/lspsaga/init.lua, lua/lspsaga/window.lua
change the ui of show_buf/line/cursor diagnostics ui.
=> version 0.2.8

lua/lspsaga/showdiag.lua
increase is an integer and doesn't have a len.
=> (showdiag) Fix height calculation

lua/lspsaga/definition.lua
=> Clear the bindings for the node buffer only

README.md
Corrected text from markdown_line to markdown_inline
=> feat: corrected text from markdown_line to markdown_inline

lua/lspsaga/hover.lua
=> feat(hover): add syntax highlighting for tailwindcss

lua/lspsaga/health.lua
This PR fixes deprecated functions for check health on new vim version
=> feat: use new functions for health check

lua/lspsaga/symbol/winbar.lua
Icon maybe nil, so it cannot simply concatenate
=> fix: icon maybe nil on winbar

lua/lspsaga/diagnostic/show.lua
Saw this mistake while working on my colorscheme.
=> Fix: Correct diagnostic hl group name

lua/lspsaga/init.lua
=> fix: add more requirements to enable `lspsaga.symbol.head`

lua/lspsaga/hover.lua
=> fix(hover): Fix hover if args is None

lua/lspsaga/callhierarchy.lua, lua/lspsaga/codeaction/init.lua
This is more or less a follow-up fix (like #1149) :)
=> fix(callhierarchy, codeaction): properly handle winhl changes

lua/lspsaga/diagnostic/show.lua
Fix show_diagnostics() if no args is provided
=> fix(diagnostics): Fix show_diagnostics() if no args is provided

lua/lspsaga/callhierarchy.lua, lua/lspsaga/floaterm.lua, lua/lspsaga/symbol/init.lua
Description:
This pull request includes the following commits:
1. fix: fix cursor set for jdtls
2. fix: use lsp jump instead of vim edit to open jdt:// protocol buffer
3. feat: supports specifying terminal cwd
4. fix: fix error caused by invalid buf， maybe caused by defer function
Please review the changes. Thank you!
=> Dev: fix jump and error, support terminal cwd

lua/lspsaga/symbol/winbar.lua
close: https://github.com/nvimdev/lspsaga.nvim/issues/1362
=> fix: escape char % is not handled

lua/lspsaga/diagnostic/show.lua
=> fix: sagadiagnostc should be sagadiagnostic

lua/lspsaga/diagnostic/init.lua
=> fix(diagnostics): propagate options to `vim.diagnostics.goto_{next,prev}` to enable severity filter

README.md
I just fixed a small typo in the readme that I noticed when looking at the plugin
=> Fixed a typo in the readme that bugged me
